<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/learn-php/13Authentication/server/">Országok</a>

        <?php if ( $params["isAuthorized"]): ?>
            <form action="/learn-php/13Authentication/server/logout" method="POST">
                <button class="btn btn-outline-danger" type="submit">Logout</button>
            </form>
        <?php endif; ?>

    </nav>
    <?= $params['content'] ?>

</body>

</html>